//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Contracts = new HashSet<Contracts>();
            this.Maintance = new HashSet<Maintance>();
            this.violations = new HashSet<violations>();
        }
    
        public int Carid { get; set; }

        [Required(ErrorMessage = "required")]
        public string CarNo { get; set; }
        [Required(ErrorMessage = "Name is Required. It cannot be empty")]
        public string CarColor { get; set; }
        public Nullable<int> CarBoardNo { get; set; }
        public string CarBoardType { get; set; }
        public string CarModel { get; set; }
        public string CarType { get; set; }
        public string SkeltonNo { get; set; }
        public string AppNo { get; set; }
        public Nullable<System.DateTime> AppStartDate { get; set; }
        public string AppEndDate { get; set; }
        public string InsurNo { get; set; }
        public string InsurCompany { get; set; }
        public Nullable<System.DateTime> InsurDate { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> DayRentValue { get; set; }
        public Nullable<decimal> DayKmeterValue { get; set; }
        public Nullable<decimal> HourRentValue { get; set; }
        public Nullable<decimal> HourKmeterValue { get; set; }
        public Nullable<decimal> MonthRentValue { get; set; }
        public Nullable<decimal> MonthKmeterValue { get; set; }
        public Nullable<decimal> DayRentValue_Driver { get; set; }
        public Nullable<decimal> DayKmeterValue_Driver { get; set; }
        public Nullable<int> CarStatus { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> OnwerId { get; set; }
        public Nullable<decimal> MinMonthRentValue { get; set; }
        public Nullable<decimal> MinHourRentValue { get; set; }
        public Nullable<int> MaintanceKmeter { get; set; }
        public Nullable<int> CaridOld { get; set; }
        public Nullable<int> CarModeltype { get; set; }
        public string InsurType { get; set; }
        public Nullable<System.DateTime> InsurDateShamal { get; set; }
        public Nullable<int> OrgId { get; set; }
    
        public virtual CarStatus CarStatus1 { get; set; }
        public virtual Models Models { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintance> Maintance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<violations> violations { get; set; }
    }
}
