//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CARACCOUNTWebEntities : DbContext
    {
        public CARACCOUNTWebEntities()
            : base("name=CARACCOUNTWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accounting> accounting { get; set; }
        public virtual DbSet<BlockServices> BlockServices { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<CarStatus> CarStatus { get; set; }
        public virtual DbSet<Cde_QidTypes> Cde_QidTypes { get; set; }
        public virtual DbSet<ContractLogs> ContractLogs { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<CostCenters> CostCenters { get; set; }
        public virtual DbSet<cust> cust { get; set; }
        public virtual DbSet<Debits> Debits { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<emp> emp { get; set; }
        public virtual DbSet<FIGURES> FIGURES { get; set; }
        public virtual DbSet<FIGURES2> FIGURES2 { get; set; }
        public virtual DbSet<FingerImages> FingerImages { get; set; }
        public virtual DbSet<FUNCTIONS> FUNCTIONS { get; set; }
        public virtual DbSet<Lawsuits> Lawsuits { get; set; }
        public virtual DbSet<Maintance> Maintance { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<Months> Months { get; set; }
        public virtual DbSet<Nats> Nats { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<PaymentCodes> PaymentCodes { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<printed> printed { get; set; }
        public virtual DbSet<qids> qids { get; set; }
        public virtual DbSet<qidsDetails> qidsDetails { get; set; }
        public virtual DbSet<Recite> Recite { get; set; }
        public virtual DbSet<RentPeriods> RentPeriods { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<setup> setup { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USER_FUNCTION> USER_FUNCTION { get; set; }
        public virtual DbSet<violations> violations { get; set; }
        public virtual DbSet<ReciteOld> ReciteOld { get; set; }
        public virtual DbSet<SetupCodes> SetupCodes { get; set; }
    }
}
