
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ChangeQuantityOrdersDetails
{

    public long ChangeOrderDetId { get; set; }

    public Nullable<long> ChangeOrderId { get; set; }

    public Nullable<long> ItemId { get; set; }

    public Nullable<long> StockId { get; set; }

    public string Item_RFID { get; set; }

    public Nullable<int> Qty { get; set; }

    public Nullable<int> InStoreQty { get; set; }

    public string Item_BarCode { get; set; }

    public Nullable<long> StoreId { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<long> StockDetId { get; set; }

    public Nullable<int> InStoreItemQty { get; set; }



    public virtual ChangeQuantityOrders ChangeQuantityOrders { get; set; }

    public virtual tbl_ItemsStock tbl_ItemsStock { get; set; }

}

}
