//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.qids = new HashSet<qids>();
        }
    
        public int contractid { get; set; }
        public string ContractCode { get; set; }
        public Nullable<int> Carid { get; set; }
        public Nullable<int> custid { get; set; }
        public string type { get; set; }
        public Nullable<int> RentPeroid { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string fils { get; set; }
        public string kd { get; set; }
        public string textamount { get; set; }
        public Nullable<decimal> paymentamount { get; set; }
        public Nullable<double> RemainAmount { get; set; }
        public Nullable<double> Totalamount { get; set; }
        public string Engtextamount { get; set; }
        public Nullable<double> ExitCounter { get; set; }
        public string EnsurType { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string empid { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> ExtraKmPrice { get; set; }
        public string Part1 { get; set; }
        public string part2 { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> RentNum { get; set; }
        public string ExistTime { get; set; }
        public string ReturnTime { get; set; }
        public Nullable<double> ReturnCounter { get; set; }
        public Nullable<int> KmDaily { get; set; }
        public Nullable<bool> Finish { get; set; }
        public Nullable<double> RealReturnCounter { get; set; }
        public Nullable<decimal> CounterIncAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> AddAmount { get; set; }
        public Nullable<int> contractidOld { get; set; }
        public Nullable<long> Serial { get; set; }
        public Nullable<double> LatePrice { get; set; }
        public string DriverName { get; set; }
        public string DriverLicenceNo { get; set; }
        public Nullable<System.DateTime> DriverLicenceDate { get; set; }
        public Nullable<bool> Cancel { get; set; }
        public Nullable<int> OrgId { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual cust cust { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qids> qids { get; set; }
    }
}
