//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenters
    {
        public long costid { get; set; }
        public string costName { get; set; }
        public string costCode { get; set; }
        public string costSName { get; set; }
        public Nullable<int> costparentId { get; set; }
        public Nullable<bool> root { get; set; }
        public Nullable<decimal> Totalfromvalue { get; set; }
        public Nullable<decimal> Totaltovalue { get; set; }
        public string notes { get; set; }
        public Nullable<double> startbalancefrom { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<double> startbalanceto { get; set; }
        public Nullable<bool> balance { get; set; }
        public Nullable<int> costType { get; set; }
        public Nullable<long> ClosedTo { get; set; }
        public Nullable<bool> MainNode { get; set; }
        public Nullable<bool> ProcessFlag { get; set; }
        public Nullable<bool> display_Flag { get; set; }
        public string LastSerialNo { get; set; }
        public Nullable<int> AccLevel { get; set; }
        public Nullable<long> MainParentAccId { get; set; }
    }
}
