//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int empid { get; set; }
        public string empname { get; set; }
        public string pw { get; set; }
        public string username { get; set; }
        public string phone { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
