
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class InOrders
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public InOrders()
    {

        this.ReturnInOrders = new HashSet<ReturnInOrders>();

        this.InOrdersDetails = new HashSet<InOrdersDetails>();

    }


    public long InOrderId { get; set; }

    public Nullable<System.DateTime> InOrderDate { get; set; }

    public Nullable<int> TransferFlag { get; set; }

    public Nullable<long> StoreId_From { get; set; }

    public Nullable<int> SupplierId_From { get; set; }

    public Nullable<long> StoreId_To { get; set; }

    public string PurchaseNo { get; set; }

    public string PaymentNo { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

    public string Remarks { get; set; }

    public Nullable<decimal> InvoiceAmount { get; set; }

    public string PictureName { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<bool> IsLock { get; set; }

    public string Notes { get; set; }

    public Nullable<int> ContractId { get; set; }



    public virtual Suppliers_tbl Suppliers_tbl { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ReturnInOrders> ReturnInOrders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InOrdersDetails> InOrdersDetails { get; set; }

}

}
