//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintance
    {
        public long MainId { get; set; }
        public Nullable<System.DateTime> MainDateFrom { get; set; }
        public Nullable<System.DateTime> MainDateTo { get; set; }
        public Nullable<int> CarID { get; set; }
        public string Note { get; set; }
        public Nullable<int> Contractid { get; set; }
        public Nullable<decimal> CounterNo { get; set; }
        public string ExistTime { get; set; }
        public string ReturnTime { get; set; }
        public Nullable<int> OrgId { get; set; }
    
        public virtual Cars Cars { get; set; }
    }
}
