//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qidsDetails
    {
        public long ID { get; set; }
        public long qidid { get; set; }
        public Nullable<decimal> FromValue { get; set; }
        public Nullable<decimal> ToValue { get; set; }
        public long ACCOUNTID { get; set; }
        public Nullable<short> type { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<int> Detcode { get; set; }
        public Nullable<int> QidType { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> ActionType { get; set; }
        public Nullable<long> CostId { get; set; }
    
        public virtual qids qids { get; set; }
    }
}
