
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class RequestOutOrders
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public RequestOutOrders()
    {

        this.RequestOrdersDetails = new HashSet<RequestOrdersDetails>();

    }


    public long ReqOrderId { get; set; }

    public Nullable<System.DateTime> ReqOrderDate { get; set; }

    public Nullable<int> ReqStatusId { get; set; }

    public Nullable<int> LocationId { get; set; }

    public Nullable<int> DeptId { get; set; }

    public Nullable<long> StoreId { get; set; }

    public Nullable<int> EmpId { get; set; }

    public string Notes { get; set; }

    public string PictureName { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual Building_tbl Building_tbl { get; set; }

    public virtual RequestStatus RequestStatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RequestOrdersDetails> RequestOrdersDetails { get; set; }

    public virtual Room_tbl Room_tbl { get; set; }

}

}
