//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Recid { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string CustName { get; set; }
        public string CustTel { get; set; }
        public string CarType { get; set; }
        public string CotractNo { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> paymentamount { get; set; }
        public Nullable<decimal> RemainAmount { get; set; }
        public Nullable<int> Carid { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
