
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Room_tbl
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Room_tbl()
    {

        this.Emp_rooms = new HashSet<Emp_rooms>();

        this.OutOrders = new HashSet<OutOrders>();

        this.OutOrders1 = new HashSet<OutOrders>();

        this.tbUsersStores = new HashSet<tbUsersStores>();

        this.tbl_ItemsStock = new HashSet<tbl_ItemsStock>();

        this.RequestOutOrders = new HashSet<RequestOutOrders>();

    }


    public long Room_Id { get; set; }

    public int Floor_Id { get; set; }

    public string Room_Name { get; set; }

    public string Room_Code { get; set; }

    public string Room_NameEn { get; set; }

    public string Room_BarCode { get; set; }

    public string Room_RFID { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public bool StoreFlag { get; set; }

    public Nullable<int> DeptQuota { get; set; }

    public string IPAddress { get; set; }

    public Nullable<bool> TcpFlag { get; set; }

    public Nullable<int> ReaderId { get; set; }

    public Nullable<int> RoomTypeId { get; set; }



    public virtual Floor_tbl Floor_tbl { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Emp_rooms> Emp_rooms { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OutOrders> OutOrders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OutOrders> OutOrders1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbUsersStores> tbUsersStores { get; set; }

    public virtual tbLookups tbLookups { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_ItemsStock> tbl_ItemsStock { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RequestOutOrders> RequestOutOrders { get; set; }

}

}
