//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupCodes
    {
        public long Id { get; set; }
        public string SupCode { get; set; }
        public string CustCode { get; set; }
        public string invSaleCode { get; set; }
        public string InvpurchasesCode { get; set; }
        public string StoresCode { get; set; }
        public string ACCountCode { get; set; }
        public string Qid { get; set; }
        public string QidIn { get; set; }
        public string QidOut { get; set; }
        public string EmpCode { get; set; }
        public Nullable<long> SalInvSerial { get; set; }
        public Nullable<long> PurchInvSerial { get; set; }
        public Nullable<long> InQidSerial { get; set; }
        public Nullable<long> OutQidSerial { get; set; }
        public Nullable<long> QidSeial { get; set; }
        public string BranchCode { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
