
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Suppliers_tbl
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Suppliers_tbl()
    {

        this.InOrders = new HashSet<InOrders>();

    }


    public int Sup_code { get; set; }

    public string Sup_Name { get; set; }

    public string Sup_Ename { get; set; }

    public string Sup_tel { get; set; }

    public string Sup_fax { get; set; }

    public string Sup_email { get; set; }

    public string Sup_Address { get; set; }

    public string Sup_mailBox { get; set; }

    public string Sup_Person { get; set; }

    public string Sup_Country { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InOrders> InOrders { get; set; }

}

}
