
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_ItemsStock
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_ItemsStock()
    {

        this.ChangeQuantityOrdersDetails = new HashSet<ChangeQuantityOrdersDetails>();

        this.DestroyOrdersDetails = new HashSet<DestroyOrdersDetails>();

        this.HandOverOrdersDetails = new HashSet<HandOverOrdersDetails>();

        this.InOrdersDetails = new HashSet<InOrdersDetails>();

        this.OutOrdersDetails = new HashSet<OutOrdersDetails>();

        this.tbl_ItemsStockDetails = new HashSet<tbl_ItemsStockDetails>();

        this.TransferAssetsDetails = new HashSet<TransferAssetsDetails>();

        this.TransferOrdersDetails = new HashSet<TransferOrdersDetails>();

        this.RequestOrdersDetails = new HashSet<RequestOrdersDetails>();

    }


    public long StockId { get; set; }

    public long Item_Id { get; set; }

    public string Item_RFID { get; set; }

    public Nullable<int> ItemQty { get; set; }

    public Nullable<long> Room_Id { get; set; }

    public Nullable<int> Emp_Id { get; set; }

    public Nullable<int> Depart_Id { get; set; }

    public Nullable<System.DateTime> Item_AssDate { get; set; }

    public Nullable<System.DateTime> Item_Expire { get; set; }

    public Nullable<int> Item_StateId { get; set; }

    public string Item_BarCode { get; set; }

    public string Item_Serial { get; set; }

    public Nullable<decimal> Item_Stock_Limit { get; set; }

    public string Location { get; set; }

    public string Notes { get; set; }

    public Nullable<decimal> MainCostPrice { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> QuotaId { get; set; }

    public Nullable<int> ContractId { get; set; }

    public bool AssetFlag { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChangeQuantityOrdersDetails> ChangeQuantityOrdersDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DestroyOrdersDetails> DestroyOrdersDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HandOverOrdersDetails> HandOverOrdersDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InOrdersDetails> InOrdersDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OutOrdersDetails> OutOrdersDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_ItemsStockDetails> tbl_ItemsStockDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TransferAssetsDetails> TransferAssetsDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TransferOrdersDetails> TransferOrdersDetails { get; set; }

    public virtual Room_tbl Room_tbl { get; set; }

    public virtual Status Status { get; set; }

    public virtual Vendor_Contracts Vendor_Contracts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RequestOrdersDetails> RequestOrdersDetails { get; set; }

    public virtual Item_tbl Item_tbl { get; set; }

}

}
