
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_ItemsStockDetails
{

    public long StockDetId { get; set; }

    public Nullable<long> InOrderDetId { get; set; }

    public Nullable<long> StockId { get; set; }

    public Nullable<decimal> CostPrice { get; set; }

    public string BarCode { get; set; }

    public Nullable<int> Qty { get; set; }

    public Nullable<System.DateTime> PurchaseDate { get; set; }

    public Nullable<System.DateTime> ExpiredDate { get; set; }

    public string Notes { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual tbl_ItemsStock tbl_ItemsStock { get; set; }

}

}
