
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class tbLookups
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbLookups()
    {

        this.HandoverOrders = new HashSet<HandoverOrders>();

        this.Room_tbl = new HashSet<Room_tbl>();

    }


    public int LookupID { get; set; }

    public string LookupName { get; set; }

    public Nullable<int> Value { get; set; }

    public string LookupString { get; set; }

    public string LookupStringAr { get; set; }

    public Nullable<bool> AllowDisplay { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<int> ID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HandoverOrders> HandoverOrders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Room_tbl> Room_tbl { get; set; }

}

}
