
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class tbUsersStores
{

    public long Id { get; set; }

    public int UserID { get; set; }

    public long StoreID { get; set; }

    public Nullable<bool> Accessing { get; set; }

    public Nullable<bool> Adding { get; set; }

    public Nullable<bool> Updating { get; set; }

    public Nullable<bool> Deleting { get; set; }

    public Nullable<bool> Importing { get; set; }

    public Nullable<bool> DeleteAll { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual Room_tbl Room_tbl { get; set; }

    public virtual tbUsers tbUsers { get; set; }

}

}
