
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class tbUsers
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbUsers()
    {

        this.tbUsersPages = new HashSet<tbUsersPages>();

        this.tbUsersStores = new HashSet<tbUsersStores>();

        this.tbUsersMainCats = new HashSet<tbUsersMainCats>();

        this.tbUsersDepts = new HashSet<tbUsersDepts>();

    }


    public int UserID { get; set; }

    public Nullable<int> EmpId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public string info { get; set; }

    public string FingerPrintID { get; set; }

    public Nullable<int> RoleID { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public string OTPCode { get; set; }



    public virtual tbUsersRoles tbUsersRoles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbUsersPages> tbUsersPages { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbUsersStores> tbUsersStores { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbUsersMainCats> tbUsersMainCats { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbUsersDepts> tbUsersDepts { get; set; }

}

}
