
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class TransferAssets
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TransferAssets()
    {

        this.TransferAssetsDetails = new HashSet<TransferAssetsDetails>();

    }


    public long TansId { get; set; }

    public Nullable<System.DateTime> TransDate { get; set; }

    public Nullable<int> TransType { get; set; }

    public Nullable<int> TransEmpId_From { get; set; }

    public Nullable<long> TransRoomId_From { get; set; }

    public Nullable<int> TransDeptId_From { get; set; }

    public Nullable<int> TransEmpId_To { get; set; }

    public Nullable<long> TransRoomId_To { get; set; }

    public Nullable<int> TransDeptId_To { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TransferAssetsDetails> TransferAssetsDetails { get; set; }

}

}
