
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class TransferAssetsDetails
{

    public long TansDetId { get; set; }

    public Nullable<long> TansId { get; set; }

    public Nullable<long> StockId { get; set; }

    public Nullable<int> EmpId { get; set; }

    public Nullable<long> RoomId { get; set; }

    public Nullable<int> DeptId { get; set; }

    public Nullable<int> StatusId { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual TransferAssets TransferAssets { get; set; }

    public virtual tbl_ItemsStock tbl_ItemsStock { get; set; }

}

}
