
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class vwAllOrders
{

    public long UniqueId { get; set; }

    public Nullable<long> ItemId { get; set; }

    public string Item_Name { get; set; }

    public Nullable<int> Qty { get; set; }

    public Nullable<long> StoreId { get; set; }

    public Nullable<System.DateTime> TranDate { get; set; }

    public string Item_RFID { get; set; }

    public string StoreName { get; set; }

    public Nullable<int> EmpId { get; set; }

    public Nullable<int> DeptId { get; set; }

    public string TransactionName { get; set; }

}

}
