//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployees
    {
        public int Id { get; set; }
        public string First_Name_Ar { get; set; }
        public string Second_Name_Ar { get; set; }
        public string Third_Name_Ar { get; set; }
        public string Fourth_Name_Ar { get; set; }
        public string FULL_NAME_AR { get; set; }
        public string First_Name_En { get; set; }
        public string Second_Name_En { get; set; }
        public string Third_Name_En { get; set; }
        public string Fourth_Name_En { get; set; }
        public string FULL_NAME_En { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Internal_Phone_Ext { get; set; }
        public string Civil_Id { get; set; }
        public Nullable<System.DateTime> Civil_Id_Expire_Date { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<int> Country_Id { get; set; }
        public Nullable<int> City_Id { get; set; }
        public string Region { get; set; }
        public string Street { get; set; }
        public string Building_Number { get; set; }
        public string Address { get; set; }
        public string Residency_Id { get; set; }
        public Nullable<System.DateTime> Residency_Id_Expire_Date { get; set; }
        public string Passport_Id { get; set; }
        public Nullable<System.DateTime> Passport_Id_Expire_Date { get; set; }
        public string Fingerprint_Id { get; set; }
        public Nullable<int> Bank_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> Job_Id { get; set; }
        public Nullable<int> Education_Level_Id { get; set; }
        public Nullable<int> Education_Qualification_Id { get; set; }
        public Nullable<int> Job_Degree_Id { get; set; }
        public Nullable<int> Job_Classification_Id { get; set; }
        public Nullable<int> Job_Level_Id { get; set; }
        public Nullable<int> Education_Level_Country_Id { get; set; }
        public string Education_Level_Name { get; set; }
        public string Bank_Account { get; set; }
        public Nullable<System.DateTime> GPF_Join_Date { get; set; }
        public Nullable<System.DateTime> GPF_End_Date { get; set; }
        public Nullable<int> Is_Deactivated { get; set; }
        public Nullable<System.DateTime> Deactivated_Date { get; set; }
        public Nullable<System.DateTime> First_Job_Date { get; set; }
        public Nullable<System.DateTime> End_Job_Date_Before_GPF { get; set; }
        public string Salary { get; set; }
        public string Salary_Cross { get; set; }
        public Nullable<int> Allow_Overtime { get; set; }
        public Nullable<int> Marital_Status_Id { get; set; }
        public Nullable<int> Children_Count { get; set; }
        public Nullable<int> Office_Location_Id { get; set; }
        public Nullable<int> Contract_Type { get; set; }
        public Nullable<int> Is_Delegated { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<System.DateTime> Deleted_at { get; set; }
        public string CountryTitleAr { get; set; }
        public string CountryTitleEN { get; set; }
        public string CityTitleAr { get; set; }
        public string CityTitleEn { get; set; }
        public string BankTitleAr { get; set; }
        public string BankTitleEn { get; set; }
        public string DeptTitle { get; set; }
        public Nullable<int> Manager_Id { get; set; }
        public string ManagerFullNameAr { get; set; }
        public string ManagerFullNameEn { get; set; }
        public string ManagerEmail { get; set; }
        public string JobTitle { get; set; }
        public string EducationLevelTitleAr { get; set; }
        public string EducationLevelTitleEn { get; set; }
        public string EducationQualificationTitleAr { get; set; }
        public string EducationQualificationTitleEn { get; set; }
        public string JobDegreeTitleAr { get; set; }
        public string JobDegreeTitleEn { get; set; }
        public string JobClassificationAr { get; set; }
        public string JobClassificationEn { get; set; }
        public string JobLevelAr { get; set; }
        public string Job_LevelEn { get; set; }
        public string MaritalStatusAr { get; set; }
        public string MaritalStatusEn { get; set; }
    }
}
