
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class vwInOrderDetails
{

    public string StoreName { get; set; }

    public string CreatedByFullName { get; set; }

    public string UpdateByFullName { get; set; }

    public string Item_Name { get; set; }

    public string Item_NameEn { get; set; }

    public string CatSub_Name { get; set; }

    public string CatSub_NameEn { get; set; }

    public string Cat_Name { get; set; }

    public string Cat_NameEn { get; set; }

    public string CatMain_Name { get; set; }

    public string CatMain_NameEn { get; set; }

    public Nullable<int> CatSub_Id { get; set; }

    public Nullable<int> Cat_Id { get; set; }

    public Nullable<int> CatMain_Id { get; set; }

    public long InOrderDetId { get; set; }

    public Nullable<long> InOrderId { get; set; }

    public Nullable<long> ItemId { get; set; }

    public string Item_RFID { get; set; }

    public Nullable<long> StockId { get; set; }

    public string Item_BarCode { get; set; }

    public Nullable<int> Qty { get; set; }

    public Nullable<int> InStoreQty { get; set; }

    public Nullable<System.DateTime> ExpiredDate { get; set; }

    public Nullable<long> StoreId { get; set; }

    public Nullable<bool> CountableFlag { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> InOrderDate { get; set; }

    public Nullable<int> SupplierId_From { get; set; }

    public Nullable<long> StoreId_To { get; set; }

    public string PurchaseNo { get; set; }

    public string PaymentNo { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

    public string Remarks { get; set; }

    public string Notes { get; set; }

    public Nullable<decimal> InvoiceAmount { get; set; }

    public string Sup_Name { get; set; }

    public string Sup_Ename { get; set; }

    public Nullable<long> StoreId_From { get; set; }

}

}
