
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class vwItemsStock
{

    public long StockId { get; set; }

    public long Item_Id { get; set; }

    public string Item_RFID { get; set; }

    public Nullable<int> ItemQty { get; set; }

    public Nullable<long> Room_Id { get; set; }

    public Nullable<int> Emp_Id { get; set; }

    public Nullable<int> Depart_Id { get; set; }

    public Nullable<System.DateTime> Item_AssDate { get; set; }

    public Nullable<System.DateTime> Item_Expire { get; set; }

    public Nullable<int> Item_StateId { get; set; }

    public string Item_BarCode { get; set; }

    public string Item_Serial { get; set; }

    public Nullable<decimal> Item_Stock_Limit { get; set; }

    public string Notes { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> QuotaId { get; set; }

    public string Item_Name { get; set; }

    public string Item_NameEn { get; set; }

    public string Room_Name { get; set; }

    public string Room_NameEn { get; set; }

    public string Floor_Name { get; set; }

    public string Floor_NameEn { get; set; }

    public string Building_Name { get; set; }

    public string Building_NameEn { get; set; }

    public Nullable<int> Floor_Id { get; set; }

    public Nullable<int> Building_Id { get; set; }

    public string AName { get; set; }

    public string EName { get; set; }

    public string Unit_Name { get; set; }

    public string Unit_NameEn { get; set; }

    public Nullable<bool> CountableFlag { get; set; }

    public Nullable<int> Age { get; set; }

}

}
