
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class vwTransferAssests
{

    public long TansDetId { get; set; }

    public Nullable<long> TansId { get; set; }

    public Nullable<long> StockId { get; set; }

    public Nullable<int> EmpId { get; set; }

    public Nullable<long> RoomId { get; set; }

    public Nullable<int> DeptId { get; set; }

    public Nullable<System.DateTime> TransDate { get; set; }

    public Nullable<int> TransType { get; set; }

    public Nullable<int> TransEmpId_From { get; set; }

    public Nullable<long> TransRoomId_From { get; set; }

    public Nullable<int> TransDeptId_From { get; set; }

    public Nullable<int> TransEmpId_To { get; set; }

    public Nullable<long> TransRoomId_To { get; set; }

    public Nullable<int> TransDeptId_To { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public long Item_Id { get; set; }

    public string Item_RFID { get; set; }

    public Nullable<int> ItemQty { get; set; }

    public string Item_Name { get; set; }

    public string Item_NameEn { get; set; }

    public string Room_Name { get; set; }

    public string Room_NameEn { get; set; }

    public string RoomNameFrom { get; set; }

    public string RoomToName { get; set; }

    public string FloorNameFrom { get; set; }

    public string FloorNameTo { get; set; }

    public Nullable<int> StatusId { get; set; }

}

}
