//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetsManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounting
    {
        public long accountid { get; set; }
        public string AccountCode { get; set; }
        public string accountname { get; set; }
        public string AccountSName { get; set; }
        public Nullable<int> AccountparentId { get; set; }
        public Nullable<bool> root { get; set; }
        public Nullable<decimal> Totalfromvalue { get; set; }
        public Nullable<decimal> Totaltovalue { get; set; }
        public string notes { get; set; }
        public Nullable<double> startbalancefrom { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<double> startbalanceto { get; set; }
        public Nullable<bool> balance { get; set; }
        public Nullable<int> accountType { get; set; }
        public Nullable<long> ClosedTo { get; set; }
        public Nullable<bool> MainNode { get; set; }
        public Nullable<bool> ProcessFlag { get; set; }
        public Nullable<bool> display_Flag { get; set; }
        public Nullable<int> AccLevel { get; set; }
        public Nullable<long> MainParentAccId { get; set; }
        public string LastSerialNo { get; set; }
        public Nullable<long> CurId { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
