//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCarApplication.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CARACCOUNTLASTEntities : DbContext
    {
        public CARACCOUNTLASTEntities()
            : base("name=CARACCOUNTLASTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accounting> accountings { get; set; }
        public virtual DbSet<BlockService> BlockServices { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CarStatu> CarStatus { get; set; }
        public virtual DbSet<Cde_QidTypes> Cde_QidTypes { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<CostCenter> CostCenters { get; set; }
        public virtual DbSet<Debit> Debits { get; set; }
        public virtual DbSet<emp> emps { get; set; }
        public virtual DbSet<FIGURE> FIGURES { get; set; }
        public virtual DbSet<FIGURES2> FIGURES2 { get; set; }
        public virtual DbSet<FUNCTION> FUNCTIONS { get; set; }
        public virtual DbSet<Lawsuit> Lawsuits { get; set; }
        public virtual DbSet<Maintance> Maintances { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<PaymentCode> PaymentCodes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<printed> printeds { get; set; }
        public virtual DbSet<qid> qids { get; set; }
        public virtual DbSet<qidsDetail> qidsDetails { get; set; }
        public virtual DbSet<Recite> Recites { get; set; }
        public virtual DbSet<RentPeriod> RentPeriods { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<setup> setups { get; set; }
        public virtual DbSet<USER_FUNCTION> USER_FUNCTION { get; set; }
        public virtual DbSet<violation> violations { get; set; }
        public virtual DbSet<SetupCode> SetupCodes { get; set; }
        public virtual DbSet<FingerImage> FingerImages { get; set; }
        public virtual DbSet<cust> custs { get; set; }
        public virtual DbSet<Nat> Nats { get; set; }
    }
}
