//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetsManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cust
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cust()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int custid { get; set; }
        public string custname { get; set; }
        public string CustEnName { get; set; }
        public Nullable<int> NatID { get; set; }
        public string NatIdType { get; set; }
        public Nullable<System.DateTime> NatIdDate { get; set; }
        public string NatIdSource { get; set; }
        public string civilid { get; set; }
        public string phone { get; set; }
        public string nationality { get; set; }
        public string address { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string LicenceNo { get; set; }
        public string LicenceSource { get; set; }
        public Nullable<System.DateTime> LicenceStartDate { get; set; }
        public Nullable<System.DateTime> LicenceEndDate { get; set; }
        public string FatherName { get; set; }
        public string FatherNatId { get; set; }
        public string FatherNatIdSource { get; set; }
        public Nullable<System.DateTime> FatherNatIdDate { get; set; }
        public string FatherTel { get; set; }
        public string FatherMoblie { get; set; }
        public string FatherAddress { get; set; }
        public string FatherCity { get; set; }
        public string WorkAddress { get; set; }
        public string blockno { get; set; }
        public string region { get; set; }
        public string st { get; set; }
        public string house { get; set; }
        public string Floor { get; set; }
        public string Building { get; set; }
        public string LicenceType { get; set; }
        public Nullable<int> OrgId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual Nat Nat { get; set; }
    }
}
