//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetsManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCTION
    {
        public int ID { get; set; }
        public string TEXT { get; set; }
        public string NAME { get; set; }
        public Nullable<int> Type { get; set; }
        public string TypeDesc { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
