//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetsManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class printed
    {
        public long ID { get; set; }
        public int contractid { get; set; }
        public Nullable<int> pmonth { get; set; }
        public Nullable<int> pyear { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
