//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetsManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recite()
        {
            this.qids = new HashSet<qid>();
        }
    
        public long reciteid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> ReciteAmount { get; set; }
        public string textamount { get; set; }
        public string Engtextamount { get; set; }
        public string kd { get; set; }
        public Nullable<int> fils { get; set; }
        public Nullable<int> contractid { get; set; }
        public Nullable<int> type { get; set; }
        public string description { get; set; }
        public Nullable<bool> get { get; set; }
        public string Notes { get; set; }
        public string RecitePersonName { get; set; }
        public string AccountantName { get; set; }
        public string ManagerName { get; set; }
        public string ChequeNo { get; set; }
        public string GetPersonName { get; set; }
        public string CarNo { get; set; }
        public string ContractNo { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> PayType { get; set; }
        public Nullable<int> RecCode { get; set; }
        public Nullable<int> OrgId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qid> qids { get; set; }
    }
}
