//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetsManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class setup
    {
        public Nullable<int> empid { get; set; }
        public Nullable<int> custid { get; set; }
        public Nullable<int> reciteid { get; set; }
        public Nullable<int> rentid { get; set; }
        public Nullable<int> blockid { get; set; }
        public Nullable<int> contractid { get; set; }
        public Nullable<int> ownerid { get; set; }
        public string CompanyName { get; set; }
        public string CompanyName1 { get; set; }
        public string CompanyOwner { get; set; }
        public string address { get; set; }
        public string Engaddress { get; set; }
        public string Tel { get; set; }
        public string logon { get; set; }
        public string AreaDesc { get; set; }
        public int Code { get; set; }
        public string Part1 { get; set; }
        public string Part2 { get; set; }
        public string ArbTitle { get; set; }
        public string EngTitle { get; set; }
        public string ArbTelTitle { get; set; }
        public string EngTelTitle { get; set; }
        public long ID { get; set; }
        public byte[] Logo { get; set; }
        public string ArbMobile { get; set; }
        public string EngMobile { get; set; }
        public string fax { get; set; }
        public string Engfax { get; set; }
        public Nullable<short> custaccid { get; set; }
        public Nullable<short> suppaccid { get; set; }
        public Nullable<int> changeid { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<int> accountid { get; set; }
        public Nullable<int> qidid { get; set; }
        public Nullable<short> salesaccid { get; set; }
        public Nullable<long> salesAgalaccid { get; set; }
        public Nullable<short> purchaseaccid { get; set; }
        public Nullable<long> purchaseAgalaccid { get; set; }
        public Nullable<long> boxaccid { get; set; }
        public Nullable<long> bankaccid { get; set; }
        public Nullable<long> PurReorderaccid { get; set; }
        public Nullable<long> SalReorderaccid { get; set; }
        public Nullable<long> PurReorderAgalaccid { get; set; }
        public Nullable<long> SalReorderAgalaccid { get; set; }
        public Nullable<long> Discountaccid { get; set; }
        public Nullable<long> Paymentsaccid { get; set; }
        public Nullable<long> purchasePayaccid { get; set; }
        public Nullable<long> Mainsalesaccid { get; set; }
        public Nullable<long> MainPurchaseaccid { get; set; }
        public Nullable<long> OsalAccId { get; set; }
        public Nullable<long> DeductAccId { get; set; }
        public Nullable<long> MovmentProfitsAccid { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
