//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=./;Initial Catalog=GPFEmployees;Persist Security Info=True;User ID=db" +
            "user;Password=geAn9s#>>A")]
        public string TempConn {
            get {
                return ((string)(this["TempConn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=gpfemployeesdbserver.database.windows.net;Initial Catalog=EmployeesDa" +
            "tabase;Persist Security Info=True;User ID=EmployeesDBUser;Password=\"m=gvSL*$mp{E" +
            "5t+4ApY\"")]
        public string Live {
            get {
                return ((string)(this["Live"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=gpfemployeesdbserver.database.windows.net;Initial Catalog=EmployeesDa" +
            "tabase;Persist Security Info=True;User ID=EmployeesDBUser;Password=\"m=gvSL*$mp{E" +
            "5t+4ApY\"")]
        public string GPFAHRConnectionString {
            get {
                return ((string)(this["GPFAHRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=./;Initial Catalog=GPFAssetsV1;Persist Security Info=True;User ID=Ass" +
            "etUserDB;Password=kdb34rb!@301nja#1")]
        public string AssetsLive {
            get {
                return ((string)(this["AssetsLive"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=./;Initial Catalog=GPFAssetsV1;Persist Security Info=True;User ID=dbu" +
            "ser;Password=geAn9s#>>A")]
        public string GPFAAssetsConnectionString {
            get {
                return ((string)(this["GPFAAssetsConnectionString"]));
            }
        }
    }
}
